name: pomogachi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  animated_reorderable_list: ^1.3.0
  circle_progress_bar: ^0.1.3
  flutter:
    sdk: flutter
  flutter_slidable: ^4.0.3
  flutter_slidable_plus: ^0.1.0
  home_widget: ^0.7.0 
  http: ^1.6.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  percent_indicator: ^4.2.5
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - data/data.json
    - data/queue.json
    - data/pomodoros.json
